Update all dependencies
kobotoolbox/reports pull request #178
Opened 2023-04-05 19:25 UTC by JacquelineMorrissette

### Description
Update the dependencies for Python and Nodejs

2023-05-18 21:38 UTC, jnm requested changes

2023-05-18 21:38 UTC, jnm commented on jsapp/package-lock.json
Something seems fishy here. Possibly a too-old version of npm was used to run the updates?

2023-05-18 21:40 UTC, jnm commented
Seems good to me after fixing `package-lock.json`

- [x]  `3.6.4` (new jQuery version) appears in the built source, indicating that the new dependencies are being used
- [x] app runs
- [x] can create new survey
- [x] can add questions to survey
- [x] can collect data with survey
- [x] can sync data
- [x] can generate html report
- [x] can generate pdf report
- [x] can generate docx report

2023-05-23 03:23 UTC, JacquelineMorrissette commented on jsapp/package-lock.json
I fixed the `lockfileVersion`, but not necessarily the way we wanted. I tested this to the best of my ability but I was struggling to test it due to local Enketo issues

2023-05-30 13:34 UTC, merged